use_frameworks!

platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'CloudPay_Example' do
#  pod 'CloudPay', :path => '../'
pod 'CloudPay'
  target 'CloudPay_Tests' do
    inherit! :search_paths

    
  end
end
